/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bookshelf.glb -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Shadow, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";
import {
  cursorActiveHandler,
  cursorInactiveHandler,
} from "Components/UserInterface/CursorOverlay";
import swal from "sweetalert";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    React: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Text: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Text001: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Text002: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Text003: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Text004: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Text005: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Text006: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Text007: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Text008: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Text009: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Text010: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Text011: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Text012: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Text013: THREE.Mesh;
    book014: THREE.Mesh;
    Text014: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube026_1: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube027_1: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube028_1: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube029_1: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube030_1: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube032_1: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube034_1: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube036_1: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube037_1: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube038_1: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube039_1: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube040_1: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube041_1: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube042_1: THREE.Mesh;
    Cube043: THREE.Mesh;
    Cube043_1: THREE.Mesh;
    Cube044: THREE.Mesh;
    Cube044_1: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube046: THREE.Mesh;
    Cube046_1: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube047_1: THREE.Mesh;
    Cube048: THREE.Mesh;
    Cube048_1: THREE.Mesh;
    Cube049: THREE.Mesh;
    Cube049_1: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube050_1: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube051_1: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube052_1: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube054_1: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube055_1: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cube056_1: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube057_1: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube058_1: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube059_1: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube060_1: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube061_1: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube062_1: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube063_1: THREE.Mesh;
    Mesh006: THREE.Mesh;
    Mesh006_1: THREE.Mesh;
  };
  materials: {
    SIde: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    reactText: THREE.MeshStandardMaterial;
    pages: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["pages.003"]: THREE.MeshStandardMaterial;
    ["Material.027"]: THREE.MeshStandardMaterial;
    ["pages.004"]: THREE.MeshStandardMaterial;
    ["Material.028"]: THREE.MeshStandardMaterial;
    ["pages.005"]: THREE.MeshStandardMaterial;
    ["Material.029"]: THREE.MeshStandardMaterial;
    ["pages.006"]: THREE.MeshStandardMaterial;
    ["Material.030"]: THREE.MeshStandardMaterial;
    ["pages.007"]: THREE.MeshStandardMaterial;
    ["Material.031"]: THREE.MeshStandardMaterial;
    ["pages.008"]: THREE.MeshStandardMaterial;
    ["Material.032"]: THREE.MeshStandardMaterial;
    ["pages.009"]: THREE.MeshStandardMaterial;
    ["Material.033"]: THREE.MeshStandardMaterial;
    ["pages.010"]: THREE.MeshStandardMaterial;
    ["Material.034"]: THREE.MeshStandardMaterial;
    ["pages.011"]: THREE.MeshStandardMaterial;
    ["Material.035"]: THREE.MeshStandardMaterial;
    ["pages.012"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
    ["pages.013"]: THREE.MeshStandardMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["pages.014"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["pages.015"]: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
    ["pages.016"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
    ["pages.017"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["pages.018"]: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["pages.019"]: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["pages.020"]: THREE.MeshStandardMaterial;
    ["Material.044"]: THREE.MeshStandardMaterial;
    ["pages.021"]: THREE.MeshStandardMaterial;
    ["Material.045"]: THREE.MeshStandardMaterial;
    ["pages.022"]: THREE.MeshStandardMaterial;
    ["Material.046"]: THREE.MeshStandardMaterial;
    ["pages.023"]: THREE.MeshStandardMaterial;
    ["Material.047"]: THREE.MeshStandardMaterial;
    ["pages.024"]: THREE.MeshStandardMaterial;
    ["Material.048"]: THREE.MeshStandardMaterial;
    ["pages.025"]: THREE.MeshStandardMaterial;
    ["Material.049"]: THREE.MeshStandardMaterial;
    ["pages.026"]: THREE.MeshStandardMaterial;
    ["Material.050"]: THREE.MeshStandardMaterial;
    ["pages.027"]: THREE.MeshStandardMaterial;
    ["Material.051"]: THREE.MeshStandardMaterial;
    ["pages.028"]: THREE.MeshStandardMaterial;
    ["Material.052"]: THREE.MeshStandardMaterial;
    ["pages.029"]: THREE.MeshStandardMaterial;
    ["Material.053"]: THREE.MeshStandardMaterial;
    ["pages.030"]: THREE.MeshStandardMaterial;
    ["Material.054"]: THREE.MeshStandardMaterial;
    ["pages.031"]: THREE.MeshStandardMaterial;
    ["Material.055"]: THREE.MeshStandardMaterial;
    ["pages.032"]: THREE.MeshStandardMaterial;
    ["Material.056"]: THREE.MeshStandardMaterial;
    ["pages.033"]: THREE.MeshStandardMaterial;
    ["Material.057"]: THREE.MeshStandardMaterial;
    ["pages.034"]: THREE.MeshStandardMaterial;
    ["Material.058"]: THREE.MeshStandardMaterial;
    ["pages.035"]: THREE.MeshStandardMaterial;
    ["Material.059"]: THREE.MeshStandardMaterial;
    ["pages.036"]: THREE.MeshStandardMaterial;
    ["Material.060"]: THREE.MeshStandardMaterial;
    ["pages.037"]: THREE.MeshStandardMaterial;
    ["Material.061"]: THREE.MeshStandardMaterial;
    ["pages.038"]: THREE.MeshStandardMaterial;
    ["Material.062"]: THREE.MeshStandardMaterial;
    ["pages.039"]: THREE.MeshStandardMaterial;
    ["Material.063"]: THREE.MeshStandardMaterial;
    ["pages.040"]: THREE.MeshStandardMaterial;
    ["Material.064"]: THREE.MeshStandardMaterial;
    ["Material.065"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/Models/bookshelf.glb`
  ) as GLTFResult;
  const soundEffect = new Audio(`${process.env.PUBLIC_URL}/audio/winner.wav`);
  return (
    <group {...props} dispose={null} scale={0.45} position={[4, 0, 5.5]}>
      <RigidBody type="fixed" colliders="cuboid">
        <group
          position={[4.268, 5.008, -0.43]}
          rotation={[0, 0, -0.226]}
          scale={[0.176, 0.761, 0.57]}
          onClick={() => window.open("https://react.dev/")}
        >
          <mesh
            geometry={nodes.Cube001.geometry}
            material={materials.reactText}
          />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.React.geometry}
            material={materials.pages}
            position={[-0.369, -0.827, -0.989]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[0.362, 0.483, 1.56]}
          />
        </group>
        <group
          position={[2.771, 4.966, -0.398]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://www.w3schools.com/html/")}
        >
          <mesh
            geometry={nodes.Cube004.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Cube004_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[3.622, 4.966, -0.398]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://nextjs.org/")}
        >
          <mesh
            geometry={nodes.Cube012.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text001.geometry}
            material={materials.pages}
            position={[-0.436, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[2.45, 4.966, -0.398]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://www.w3schools.com/Css/")}
        >
          <mesh
            geometry={nodes.Cube013.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text002.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[4.045, 6.983, -0.34]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() =>
            window.open(
              "https://www.adobe.com/products/photoshop/how-to-use.html"
            )
          }
        >
          <mesh
            geometry={nodes.Cube014.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text003.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[3.619, 6.954, -0.34]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() =>
            window.open(
              "https://www.adobe.com/be_nl/products/illustrator/free-trial-download.html"
            )
          }
        >
          <mesh
            geometry={nodes.Cube015.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text004.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[1.968, 6.963, -0.281]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() =>
            window.open("https://helpx.adobe.com/xd/get-started.html")
          }
        >
          <mesh
            geometry={nodes.Cube016.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text005.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[1.424, 6.998, -0.281]}
          scale={[0.164, 0.714, 0.534]}
          onClick={(event) => {
            event.stopPropagation();
            swal("You found my favourite book! now have a look for yourself");
            window.localStorage.setItem("Read", "complete");
            window.dispatchEvent(new Event("storage"));

            setTimeout(() => {
              window.open("https://www.figma.com/");
            }, 2000);
          }}
        >
          <mesh
            geometry={nodes.Cube017.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text006.geometry}
            material={materials.pages}
            position={[-0.44, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[0.457, 4.966, -0.017]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://nodejs.org/docs/latest/api/")}
        >
          <mesh
            geometry={nodes.Cube018.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text007.geometry}
            material={materials.pages}
            position={[-0.44, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[0.91, 4.966, -0.246]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://github.com/expressjs/express")}
        >
          <mesh
            geometry={nodes.Cube019.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Cube019_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text008.geometry}
            material={materials.pages}
            position={[-0.402, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[-1.637, 4.966, 0.022]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://www.php.net/")}
        >
          <mesh
            geometry={nodes.Cube020.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.Cube020_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text009.geometry}
            material={materials.pages}
            position={[-0.482, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[-2.025, 4.966, -0.227]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://laravel.com/")}
        >
          <mesh
            geometry={nodes.Cube021.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            geometry={nodes.Cube021_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text010.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[-3.202, 4.966, 0]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://www.shopify.com/be")}
        >
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["Material.022"]}
          />
          <mesh
            geometry={nodes.Cube022_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text011.geometry}
            material={materials.pages}
            position={[-0.489, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[-4.048, 4.966, 0.032]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://craftcms.com/")}
        >
          <mesh
            geometry={nodes.Cube023.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text012.geometry}
            material={materials.pages}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <group
          position={[-0.598, 4.966, -0.411]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() => window.open("https://threejs.org/")}
        >
          <mesh
            geometry={nodes.Cube024.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            geometry={nodes.Cube024_1.geometry}
            material={materials.pages}
          />
          <mesh
            geometry={nodes.Text013.geometry}
            material={materials.pages}
            position={[-0.472, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </group>
        <mesh
          geometry={nodes.book014.geometry}
          material={materials.pages}
          position={[-3.989, 6.975, -0.333]}
          scale={[0.164, 0.714, 0.534]}
          onClick={() =>
            window.open("https://learn.microsoft.com/en-us/dotnet/csharp/")
          }
        >
          <mesh
            geometry={nodes.Text014.geometry}
            material={nodes.Text014.material}
            position={[-0.63, -0.881, -0.985]}
            rotation={[-1.571, -1.571, 0]}
            scale={[0.4, 0.534, 1.737]}
          />
        </mesh>
        <group position={[0.013, 4.966, -0.225]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube026.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Cube026_1.geometry}
            material={materials["pages.003"]}
          />
        </group>
        <group
          position={[1.355, 4.966, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube027.geometry}
            material={materials["Material.027"]}
          />
          <mesh
            geometry={nodes.Cube027_1.geometry}
            material={materials["pages.004"]}
          />
        </group>
        <group position={[1.797, 4.966, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube028.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            geometry={nodes.Cube028_1.geometry}
            material={materials["pages.005"]}
          />
        </group>
        <group position={[3.104, 4.966, -0.323]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube029.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["pages.006"]}
          />
        </group>
        <group position={[2.121, 4.966, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube030.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cube030_1.geometry}
            material={materials["pages.007"]}
          />
        </group>
        <group position={[-0.937, 4.966, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["Material.031"]}
          />
          <mesh
            geometry={nodes.Cube031_1.geometry}
            material={materials["pages.008"]}
          />
        </group>
        <group position={[-1.264, 4.966, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cube032_1.geometry}
            material={materials["pages.009"]}
          />
        </group>
        <group
          position={[-2.56, 4.966, -0.139]}
          rotation={[0, 0, -0.381]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube033.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cube033_1.geometry}
            material={materials["pages.010"]}
          />
        </group>
        <group position={[-3.602, 4.966, -0.176]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube034.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Cube034_1.geometry}
            material={materials["pages.011"]}
          />
        </group>
        <group position={[-4.388, 4.966, -0.176]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube035.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.Cube035_1.geometry}
            material={materials["pages.012"]}
          />
        </group>
        <group position={[2.326, 6.987, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube036.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            geometry={nodes.Cube036_1.geometry}
            material={materials["pages.013"]}
          />
        </group>
        <group position={[2.653, 6.987, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube037.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            geometry={nodes.Cube037_1.geometry}
            material={materials["pages.014"]}
          />
        </group>
        <group
          position={[3.132, 6.986, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube038.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            geometry={nodes.Cube038_1.geometry}
            material={materials["pages.015"]}
          />
        </group>
        <group position={[-0.271, 6.974, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube039.geometry}
            material={materials["Material.039"]}
          />
          <mesh
            geometry={nodes.Cube039_1.geometry}
            material={materials["pages.016"]}
          />
        </group>
        <group position={[0.056, 6.974, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube040.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            geometry={nodes.Cube040_1.geometry}
            material={materials["pages.017"]}
          />
        </group>
        <group position={[1.005, 6.974, -0.225]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube041.geometry}
            material={materials["Material.041"]}
          />
          <mesh
            geometry={nodes.Cube041_1.geometry}
            material={materials["pages.018"]}
          />
        </group>
        <group position={[-2.769, 6.947, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube042.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cube042_1.geometry}
            material={materials["pages.019"]}
          />
        </group>
        <group position={[-3.094, 6.947, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube043.geometry}
            material={materials["Material.043"]}
          />
          <mesh
            geometry={nodes.Cube043_1.geometry}
            material={materials["pages.020"]}
          />
        </group>
        <group
          position={[-3.536, 6.947, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube044.geometry}
            material={materials["Material.044"]}
          />
          <mesh
            geometry={nodes.Cube044_1.geometry}
            material={materials["pages.021"]}
          />
        </group>
        <group position={[-2.142, 6.967, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube045.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            geometry={nodes.Cube045_1.geometry}
            material={materials["pages.022"]}
          />
        </group>
        <group position={[-1.815, 6.967, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube046.geometry}
            material={materials["Material.046"]}
          />
          <mesh
            geometry={nodes.Cube046_1.geometry}
            material={materials["pages.023"]}
          />
        </group>
        <group position={[-0.865, 6.967, -0.225]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube047.geometry}
            material={materials["Material.047"]}
          />
          <mesh
            geometry={nodes.Cube047_1.geometry}
            material={materials["pages.024"]}
          />
        </group>
        <group position={[-2.979, 8.945, -0.225]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube048.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            geometry={nodes.Cube048_1.geometry}
            material={materials["pages.025"]}
          />
        </group>
        <group position={[-3.928, 8.945, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube049.geometry}
            material={materials["Material.049"]}
          />
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["pages.026"]}
          />
        </group>
        <group position={[-4.255, 8.945, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube050.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            geometry={nodes.Cube050_1.geometry}
            material={materials["pages.027"]}
          />
        </group>
        <group
          position={[-0.852, 8.957, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube051.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            geometry={nodes.Cube051_1.geometry}
            material={materials["pages.028"]}
          />
        </group>
        <group position={[-1.331, 8.958, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube052.geometry}
            material={materials["Material.052"]}
          />
          <mesh
            geometry={nodes.Cube052_1.geometry}
            material={materials["pages.029"]}
          />
        </group>
        <group position={[-1.658, 8.958, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube053.geometry}
            material={materials["Material.053"]}
          />
          <mesh
            geometry={nodes.Cube053_1.geometry}
            material={materials["pages.030"]}
          />
        </group>
        <group position={[2.152, 8.975, -0.225]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube054.geometry}
            material={materials["Material.054"]}
          />
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["pages.031"]}
          />
        </group>
        <group position={[1.203, 8.975, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube055.geometry}
            material={materials["Material.055"]}
          />
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["pages.032"]}
          />
        </group>
        <group position={[0.876, 8.975, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube056.geometry}
            material={materials["Material.056"]}
          />
          <mesh
            geometry={nodes.Cube056_1.geometry}
            material={materials["pages.033"]}
          />
        </group>
        <group
          position={[-0.518, 8.954, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube057.geometry}
            material={materials["Material.057"]}
          />
          <mesh
            geometry={nodes.Cube057_1.geometry}
            material={materials["pages.034"]}
          />
        </group>
        <group position={[-0.076, 8.954, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube058.geometry}
            material={materials["Material.058"]}
          />
          <mesh
            geometry={nodes.Cube058_1.geometry}
            material={materials["pages.035"]}
          />
        </group>
        <group position={[0.248, 8.954, -0.212]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube059.geometry}
            material={materials["Material.059"]}
          />
          <mesh
            geometry={nodes.Cube059_1.geometry}
            material={materials["pages.036"]}
          />
        </group>
        <group position={[3.073, 8.982, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube060.geometry}
            material={materials["Material.060"]}
          />
          <mesh
            geometry={nodes.Cube060_1.geometry}
            material={materials["pages.037"]}
          />
        </group>
        <group position={[2.747, 8.982, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube061.geometry}
            material={materials["Material.061"]}
          />
          <mesh
            geometry={nodes.Cube061_1.geometry}
            material={materials["pages.038"]}
          />
        </group>
        <group
          position={[3.867, 8.971, -0.286]}
          rotation={[0, 0, 0.179]}
          scale={[0.164, 0.714, 0.534]}
        >
          <mesh
            geometry={nodes.Cube062.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            geometry={nodes.Cube062_1.geometry}
            material={materials["pages.039"]}
          />
        </group>
        <group position={[3.388, 8.972, -0.298]} scale={[0.164, 0.714, 0.534]}>
          <mesh
            geometry={nodes.Cube063.geometry}
            material={materials["Material.063"]}
          />
          <mesh
            geometry={nodes.Cube063_1.geometry}
            material={materials["pages.040"]}
          />
        </group>
        <group
          position={[-3.389, 0.232, 0]}
          rotation={[Math.PI / 2, 0, -2.751]}
          scale={0.856}
          onClick={() => {
            soundEffect.play();
            setTimeout(() => {
              window.open(
                "https://www.flickr.com/photos/196953204@N03/53322378520/in/album-72177720312540042/"
              );
            }, 2000);
          }}
          onPointerEnter={cursorActiveHandler}
          onPointerLeave={cursorInactiveHandler}
          onPointerOut={cursorInactiveHandler}
          onPointerOver={cursorActiveHandler}
        >
          <mesh
            geometry={nodes.Mesh006.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Mesh006_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <mesh geometry={nodes.Cube.geometry} material={materials.SIde} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Wood} />
      </RigidBody>
    </group>
  );
}

useGLTF.preload(`${process.env.PUBLIC_URL}/Models/bookshelf.glb`);

export { Model as Bookshelf };
